# Generated by Django 4.2.4 on 2024-10-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_name', models.CharField(max_length=100, verbose_name='Адрес')),
                ('area', models.IntegerField(default=0, verbose_name='Площадь')),
                ('photo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'db_table': 'addresses',
                'managed': True,
            },
        ),
    ]
