# Generated by Django 4.2.4 on 2024-10-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_fixation_addressfixation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='status',
            field=models.CharField(blank=True, default='active', max_length=100),
        ),
    ]
