# Generated by Django 4.2.4 on 2024-10-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_address_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='status',
        ),
        migrations.AlterField(
            model_name='address',
            name='address_name',
            field=models.CharField(default='address', max_length=100, verbose_name='Адрес'),
        ),
    ]
