# Generated by Django 4.2.4 on 2024-10-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_address_status_alter_address_address_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='status',
            field=models.CharField(blank=True, default='active', max_length=100),
        ),
    ]
