# Generated by Django 4.2.4 on 2024-11-12 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_address_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressfixation',
            old_name='value',
            new_name='water_counter_value',
        ),
    ]
