# Generated by Django 4.2.4 on 2024-11-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_value_addressfixation_water_counter_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressfixation',
            name='pay_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
