# Generated by Django 4.2.7 on 2024-10-01 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixation',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 1, 18, 49, 26, 748837, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
