# Generated by Django 4.2.7 on 2024-10-01 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0002_alter_fixation_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='image',
            field=models.CharField(default='images/default.png'),
        ),
        migrations.AlterField(
            model_name='fixation',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 1, 18, 59, 50, 988738, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
