# Generated by Django 4.2.7 on 2024-10-01 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0003_alter_address_image_alter_fixation_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixation',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 1, 21, 57, 14, 354075, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='fixation',
            name='month',
            field=models.IntegerField(default=0, verbose_name='Месяц'),
        ),
    ]
